view:
  latitude: 12
  longitude: 12
  minZoom: 0
  maxZoom: 18
  zoom: 6
  baselayer: osm
  featurelayers:
    - roads
    - buildings
featurelayers:
  - id: roads
    title: Roads
    type: wms
    wms:
      layers: "geonode:nga_trs_roads_osm_wfpschema_sep2016"
      url: http://geonode.wfp.org/cors/geoserver/wms
    wfs:
      url: http://geonode.wfp.org/cors/geoserver/wfs
  - id: buildings
    title: OSM Buildings
